version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "08:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.NetFramework.Analyzers
    versions:
    - 3.3.2
  - dependency-name: Microsoft.CodeAnalysis.VersionCheckAnalyzer
    versions:
    - 3.3.2
  - dependency-name: Microsoft.CodeAnalysis.Analyzers
    versions:
    - 3.3.2
  - dependency-name: Microsoft.NetCore.Analyzers
    versions:
    - 3.3.2
  - dependency-name: Microsoft.CodeQuality.Analyzers
    versions:
    - 3.3.2
  - dependency-name: Microsoft.CodeAnalysis.FxCopAnalyzers
    versions:
    - 3.3.2
  - dependency-name: System.Text.Encoding.CodePages
    versions:
    - 5.0.0
  - dependency-name: Microsoft.CodeAnalysis.Common
    versions:
    - 3.8.0
  - dependency-name: Microsoft.CodeAnalysis.CSharp
    versions:
    - 3.8.0
  - dependency-name: xunit.runner.visualstudio
    versions:
    - 2.4.3
