language: csharp
mono: none

solution: Tests.sln

install:  
  - nuget install NUnit.Runners -Version 3.9.0 -OutputDirectory testrunner

script:
 - dotnet restore
 - xbuild /p:Configuration=Release Tests.sln
