language: csharp
mono: none
dotnet: 1.1.5
script:
 - dotnet restore

solution: Tests.sln

install:
  - nuget restore Tests.sln
  - nuget install NUnit.Runners -Version 3.9.0 -OutputDirectory testrunner