image: Visual Studio 2017

build: on
test: on
deploy: off

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: LeedCode.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\LeedCodeExercises\UnitTests\bin\Debug\UnitTests.dll -noshadow" -filter:"+[UnitTests*]* -[UnitTests*]*" -output:".\MyProject_coverage.xml"
- codecov -f "MyProject_coverage.xml