image: Visual Studio 2017

version: 1.0.{build}

branches:
  only:
  - master
  
clone_folder: C:\LeedCodeExercises

configuration: Debug
platform: Any CPU

#patch
assembly_info:
  patch: true
  file: 'C:\LeedCodeExercises\LeedCodeBusiness\Properties\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'  

before_build:
- nuget restore

build:
  project: CodingExercise.sln
  verbosity: minimal

test_script:
- .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:".\packages\xunit.runner.console.2.4.1\tools\net472\xunit.console.x86.exe" -targetargs:".\UnitTests\bin\Debug\UnitTests.dll -noshadow" -output:".\MyProject_coverage.xml"


#upload report
- .\packages\Codecov.1.10.0\tools\codecov.exe -f "MyProject_coverage.xml"
