image: Visual Studio 2017

version: 1.0.{build}

branches:
  only:
  - master
  
clone_folder: C:\LeedCodeExercises

configuration: Debug
platform: Any CPU

#patch
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'  

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: CodingExercise.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:administrator -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\UnitTests\bin\Debug\UnitTests.dll -noshadow" -output:".\MyProject_coverage.xml"

#upload
- codecov -f "MyProject_coverage.xml"
