image: Visual Studio 2017

before_build:
- nuget restore

build:
  project: LeedCode.sln
  verbosity: minimal

test_script:
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\xunit.runner.console.2.4.1\tools\net471\xunit.console.x86.exe" -targetargs:".\UnitTests\bin\Debug\UnitTests.dll -noshadow" -output:".\MyProject_coverage.xml"

#-filter:"+[Data*]* -[UnitTests*]*"

#upload report
- .\packages\Codecov.1.1.0\tools\codecov.exe -f "MyProject_coverage.xml"
